### ISSUE TITLE
Shader lighting not working properly

### ISSUE THREAD

**Issue by bc15kle** [lilxyzw/lilToon#30]
The ambient lighting (from the lighting tab) doesn't seem to affect the objects that use lilToon
![image](https://user-images.githubusercontent.com/42741373/180229345-4e747481-bc38-46dc-95bf-b0ec707e3a89.png)

Edit: I may mention that this problem is occurring on the Universal Render Pipeline version of the shader. I'm not sure if the problem persist on other render pipelines other than URP.

**Comment by lilxyzw** [comment]
I have fixed this issue in the dev branch. This fix will be applied in version 1.3.3

**Comment by bc15kle** [comment]
Still not fixed. It works when generating the said light only and not before generation like other shaders like urp's standard.

**Comment by lilxyzw** [comment]
Oh, I probably understood what you meant. By default lilToon does the shading in Unlit and then multiplies the sum of all lights. This is to avoid changing the look too much with lighting. In other words, the color is determined by the following calculation

```
Lit Color = Albedo (Main Color) * (Directional Light + Additional Light + Environment Light)
Shadow Color = Albedo (Main Color) * (Directional Light + Additional Light + Environment Light) * Shadow Color
```

If you want the shadow color to change depending on the environment light, set `Environment strength on shadow color` to 1. In addition, you can set the shadow color to black to get a result similar to the Lit Shader.

**Comment by bc15kle** [comment]
Thank you for your help!
